"""Where the capture, the teammate's weights and the scratch directory live.

Every research script reads these, so pointing them somewhere else is three
environment variables rather than an edit per file:

    AIGP_CAPTURE      the frame directory (default ~/Downloads/gate frames)
    AIGP_TEAMMATE_PT  the teammate's YOLO checkpoint (default ~/Downloads/best.pt)
    AIGP_WORK         intermediates such as labels and galleries (default <repo>/work)

Neither the capture nor `work/` is in the repo: the walk-around is hundreds
of megabytes and `work/` is regenerated by the scripts that read it.
"""

from __future__ import annotations

import os
from pathlib import Path

_REPO = Path(__file__).resolve().parents[1]

CAPTURE = Path(os.environ.get("AIGP_CAPTURE", "~/Downloads/gate frames")).expanduser()
TEAMMATE_PT = Path(os.environ.get("AIGP_TEAMMATE_PT", "~/Downloads/best.pt")).expanduser()
WORK = Path(os.environ.get("AIGP_WORK", str(_REPO / "work"))).expanduser()


def frames(pattern: str = "*.jpg") -> list[str]:
    """Sorted paths of the capture's frames, as strings for cv2."""
    return sorted(str(p) for p in CAPTURE.glob(pattern))
